markdown: rdiscount
pygments: true

# Template Settings
title: 'Apps and the City Cologne'
location:
- text: 'Interactive Cologne'
  url: 'http://interactive-cologne.com/hack-n-tech-startup.html'
date: '18./19. Juni 2013'
github: 'https://github.com/okfde/cologne.appsandthecity'
contact: 'jan.brennenstuhl@okfn.org'
mailinglist: 'http://lists.okfn.org/mailman/listinfo/open-data-nahverkehr'


# Navigation
navigation:
- text: 'Beispiele'
  url: '/#beispiele'
- text: 'Hack Track'
  url: '/#hacktrack'
- text: 'Daten'
  url: '/daten'
- text: 'Apps'
  url: '/apps'
